export const ME_LOADING = "ME_LOADING";
export const ME_SUCCESS = "ME_SUCCESS";
export const ME_FAIL = "ME_FAIL";

export const LOGIN_WITH_EMAIL_LOADING = "LOGIN_WITH_EMAIL_LOADING";
export const LOGIN_WITH_EMAIL_SUCCESS = "LOGIN_WITH_EMAIL_SUCCESS";
export const LOGIN_WITH_EMAIL_FAIL = "LOGIN_WITH_EMAIL_FAIL";

export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
